# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8d74ccd07b68a2ef621f08dd04c0b8ec0ece22213200ce40aa26927803aaa33c67cf5086ce3bce854e0e597671c01909141a0b8d14562418bc4e58f6b6c2fae

test:
  secret_key_base: 0def84fdc1278dca3db2b526d8b245f386a065b5ddb8402ae439b7ff4ff5ad5f9d65d3232bd81ad719d70b7a89cadb1468e55176f93500f6cfa844fd527fe13f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
